services:

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3.40.0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
    ports:
      - 7777:7777
    restart: unless-stopped

  torrent:
    container_name: "torrent"
    image: linuxserver/qbittorrent:5.0.4-libtorrentv1
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - WEBUI_PORT=7777
    restart: unless-stopped
