# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."nexus-qbittorrent-gluetun" = {
    image = "qmcgaw/gluetun:v3.40.0";
    environment = {
      "VPN_SERVICE_PROVIDER" = "mullvad";
      "VPN_TYPE" = "wireguard";
    };
    ports = [
      "7777:7777/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=gluetun"
      "--network=nexus-qbittorrent_default"
    ];
  };
  systemd.services."podman-nexus-qbittorrent-gluetun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-nexus-qbittorrent_default.service"
    ];
    requires = [
      "podman-network-nexus-qbittorrent_default.service"
    ];
    partOf = [
      "podman-compose-nexus-qbittorrent-root.target"
    ];
    wantedBy = [
      "podman-compose-nexus-qbittorrent-root.target"
    ];
  };
  virtualisation.oci-containers.containers."nexus-qbittorrent-torrent" = {
    image = "linuxserver/qbittorrent:5.1.2-libtorrentv1";
    environment = {
      "WEBUI_PORT" = "7777";
    };
    dependsOn = [
      "nexus-qbittorrent-gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:nexus-qbittorrent-gluetun"
    ];
  };
  systemd.services."podman-nexus-qbittorrent-torrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-nexus-qbittorrent-root.target"
    ];
    wantedBy = [
      "podman-compose-nexus-qbittorrent-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-nexus-qbittorrent_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f nexus-qbittorrent_default";
    };
    script = ''
      podman network inspect nexus-qbittorrent_default || podman network create nexus-qbittorrent_default
    '';
    partOf = [ "podman-compose-nexus-qbittorrent-root.target" ];
    wantedBy = [ "podman-compose-nexus-qbittorrent-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nexus-qbittorrent-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
