name: nexus-n8n

services:

  postgres:
    image: postgres:16.9
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=n8n
    volumes:
      - /var/lib/postgresql_n8n:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U user -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.118.1
    restart: always
    environment:
      - N8N_HOST=n8n.matteopacini.me
      - WEBHOOK_URL=https://n8n.matteopacini.me
      - N8N_SECURE_COOKIE=false
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/London
      - TZ=Europe/London
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=user
      - DB_POSTGRESDB_PASSWORD=password
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - /var/lib/n8n:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

