name: Build & Push System

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ATTIC_CACHE_NAME: ${{ secrets.ATTIC_CACHE_NAME }}
  ATTIC_CACHE_URL: ${{ secrets.ATTIC_CACHE_URL }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: BrightFalls
            platform: x86_64-linux
            os: ubuntu-latest
            system_attr: nixosConfigurations
            build_attr: config.system.build.toplevel
          - host: BrightFallsVM-x86_64-linux
            platform: x86_64-linux
            os: ubuntu-latest
            system_attr: nixosConfigurations
            build_attr: config.system.build.toplevel
          - host: BrightFallsVM-aarch64-linux
            platform: aarch64-linux
            os: ubuntu-24.04.arm
            system_attr: nixosConfigurations
            build_attr: config.system.build.toplevel
          - host: Nexus
            platform: x86_64-linux
            os: ubuntu-latest
            system_attr: nixosConfigurations
            build_attr: config.system.build.toplevel
          - host: CauldronLake
            platform: x86_64-linux
            os: ubuntu-latest
            system_attr: nixosConfigurations
            build_attr: config.system.build.toplevel
          - host: WorkLaptop
            platform: aarch64-darwin
            os: macos-latest
            system_attr: darwinConfigurations
            build_attr: config.system.build.toplevel
          - host: NightSprings
            platform: aarch64-darwin
            os: macos-latest
            system_attr: darwinConfigurations
            build_attr: config.system.build.toplevel

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: wimpysworld/nothing-but-nix@v6
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          hatchet-protocol: "rampage"
          witness-carnage: true
          nix-permission-edict: true

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Configure Attic cache
        run: |
          nix run nixpkgs#attic-client -- login \
            "${{ env.ATTIC_CACHE_NAME }}" "${{ env.ATTIC_CACHE_URL }}" "${{ env.ATTIC_TOKEN }}"
          nix run nixpkgs#attic-client -- use "${{ matrix.host }}"

      - name: Build system
        run: |
          nix build ".#${{ matrix.system_attr }}.${{ matrix.host }}.${{ matrix.build_attr }}"

      - uses: nick-fields/retry@v3
        name: Push system
        with:
          timeout_minutes: 7200
          max_attempts: 5
          retry_on: error
          command: nix run nixpkgs#attic-client -- push "${{ matrix.host }}" result -j 3
