name: Weekly Nix Flake Update

on:
  schedule:
    - cron: "0 0 * * 5" # Midnight UTC on Fridays
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Update flake inputs
        run: nix flake update

      - name: Check for nixpkgs changes
        id: check_changes
        run: |
          if git diff flake.lock | grep -q "^\+.*nixpkgs"; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate update summary
        if: steps.check_changes.outputs.has_changes == 'true'
        id: summary
        run: |
          {
            echo "## Nixpkgs Updated"
            echo ""
            echo "The nixpkgs input has been updated to the latest version."
            echo ""
            echo "### Changes:"
            echo '```diff'
            git diff flake.lock | grep -A 5 -B 5 "nixpkgs"
            echo '```'
          } > /tmp/pr_body.md
          cat /tmp/pr_body.md >> $GITHUB_STEP_SUMMARY

      - name: Create pull request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Weekly flake update - ${{ github.event.repository.updated_at }}"
          title: "chore: Weekly flake update - ${{ github.event.repository.updated_at }}"
          body-path: /tmp/pr_body.md
          branch: automated/flake-update-${{ github.run_number }}
          base: master
          delete-branch: true

      - name: No changes
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "No flake input updates available"
